version: '2.1'
volumes:
  resin-data: {}
services:
  spi:
    build: ./spi
    privileged: true
    restart: always
    devices:
      - "/dev/spidev1.0:/dev/spidev1.0"
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
      io.balena.features.kernel-modules: '1'
  uart:
    build: ./uart
    privileged: true
    restart: always
    devices:
      - "/dev/spidev1.0:/dev/spidev1.0"
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
      io.balena.features.kernel-modules: '1'
