version: '2.1'
services:
  # i2c:
  #   build: ./i2c
  #   privileged: true
  #   restart: always
  #   devices:
  #     - "/dev/i2c-0:/dev/i2c-0"
  #     - "/dev/i2c-2:/dev/i2c-2"
  #   volumes:
  #     - 'resin-i2c:/data'
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.kernel-modules: '1'
  # spi:
  #   build: ./spi
  #   privileged: true
  #   restart: always
  #   devices:
  #     - "/dev/spidev1.0:/dev/spidev1.0"
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.kernel-modules: '1'
  uart:
    build: ./uart
    environment:
      - UDEV=1
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
      io.balena.features.kernel-modules: '1'
